2024-07-10T08:08:25.390451 - Erreur de connexion: HTTPConnectionPool(host='selenium', port=4444): Max retries exceeded with url: /wd/hub/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f942ac82b20>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-07-10T08:08:26.500243 - Erreur de connexion: HTTPConnectionPool(host='selenium', port=4444): Max retries exceeded with url: /wd/hub/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f942ac205e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-07-10T08:08:27.565891 - Erreur de connexion: HTTPConnectionPool(host='selenium', port=4444): Max retries exceeded with url: /wd/hub/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f942ac71fd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-07-10T08:08:28.620925 - Erreur de connexion: HTTPConnectionPool(host='selenium', port=4444): Max retries exceeded with url: /wd/hub/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f942ac82a00>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-07-10T08:08:29.712050 - Erreur de connexion: HTTPConnectionPool(host='selenium', port=4444): Max retries exceeded with url: /wd/hub/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f942ac20fa0>: Failed to establish a new connection: [Errno 111] Connection refused'))
