2024-07-10T09:54:43.798791 - Erreur de connexion: HTTPConnectionPool(host='selenium', port=4444): Max retries exceeded with url: /wd/hub/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d9ed72cd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-07-10T09:54:44.842152 - Erreur de connexion: HTTPConnectionPool(host='selenium', port=4444): Max retries exceeded with url: /wd/hub/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d9ed11790>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-07-10T09:54:45.869611 - Erreur de connexion: HTTPConnectionPool(host='selenium', port=4444): Max retries exceeded with url: /wd/hub/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d9ed11190>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-07-10T09:54:46.899529 - Erreur de connexion: HTTPConnectionPool(host='selenium', port=4444): Max retries exceeded with url: /wd/hub/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d9ed721c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
