2024-07-10T08:56:01.600845 - Erreur de connexion: HTTPConnectionPool(host='selenium', port=4444): Max retries exceeded with url: /wd/hub/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd97b1dab80>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-07-10T08:56:02.692078 - Erreur de connexion: HTTPConnectionPool(host='selenium', port=4444): Max retries exceeded with url: /wd/hub/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd97b17a640>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-07-10T08:56:03.724383 - Erreur de connexion: HTTPConnectionPool(host='selenium', port=4444): Max retries exceeded with url: /wd/hub/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd97b1ccfd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
